### ISSUE TITLE
Font API down?

### ISSUE THREAD

**Issue by Correct-Syntax** [coollabsio/fonts#10]
Hello,

Not sure what is happening, but it appears that any font other than ``Roboto`` is not served from the API. A few days ago, everything was working nicely, but today I noticed the fonts were not loading and visiting the links results in a 404.

``https://api.fonts.coollabs.io/css2?family=Roboto`` works, but not ``https://api.fonts.coollabs.io/css2?family=Merriweather`` or any other font I can think of.

In any case, thank you for providing this privacy respecting alternative for fonts. 🙂

**Comment by andrasbacsai** [comment]
Oh, sorry about it. It is back online!

**Comment by Correct-Syntax** [comment]
Thank you. 🎉
