### ISSUE TITLE
api.fonts.coollabs.io (hungarumlauts issue)

### ISSUE THREAD

**Issue by vintezis** [coollabsio/fonts#15]
Szia András,

először is big thx ezért a googlefont alternatíváért!

Ami miatt írok, az az, hogy a head-ben kicserélt cdn-url esetén a font-ot betölti ugyan, de a hosszú ő/ű betűk helyén a default font jelenik meg (az eredeti GoogleFont-ban szerepelnek ezek a karakterek).

A kérdésem annyi csak, hogy ez egy limitáció (fizikailag egy más font-file kerül betöltésre), vagy egyszerűen én csinálok valamit rosszul.

Előre is köszi a választ,
üdv

Tamás

**Comment by andrasbacsai** [comment]
Szia, meg tudnád most nézni? Pár dolgot javítottam.

**Comment by vintezis** [comment]
Megnéztem (most egy másik fonttal), és ez van:
![coollabs-font-issue](https://github.com/coollabsio/fonts/assets/60468671/c659b916-fdbb-445d-8b46-440a23d821c8)

Vagy egyszerűen én csinálok vmit rosszul?

**Comment by andrasbacsai** [comment]
Köszi, megnézem hogy mi lehet a gond!

**Comment by andrasbacsai** [comment]
Fixed a lot of issues. It should work now. If not, please open an issue.
