### ISSUE TITLE
Loading multiple fonts at once with display swap not working

### ISSUE THREAD

**Issue by jploch** [coollabsio/fonts#17]
This works:
https://api.fonts.coollabs.io/css2?family=Space+Grotesk&family=Space+Mono&family=Aguafina+Script&family=Audiowide

This doesn't (only returning some fonts):
https://api.fonts.coollabs.io/css2?family=Space+Grotesk&family=Space+Mono&family=Aguafina+Script&family=Audiowide&display=swap

**Comment by andrasbacsai** [comment]
I see all the fonts with the swap option. What is missing or incorrect?

**Comment by jploch** [comment]
Not sure if it's a cache thing on my end. The first link is returning all fonts correctly but the second link is only returning "Space Grotesk". I had some issues when adding the display=swap parameter with other links as well.

**Comment by andrasbacsai** [comment]
![image](https://github.com/coollabsio/fonts/assets/5845193/3d23fccc-408d-4c97-9ff4-c08ec77e82c2)

Can you please check it now? I purged the cache.

**Comment by jploch** [comment]
Thanks for looking into it! Now it works correctly. Is there a way to add cache busting to the request url?

**Comment by sudomistress** [comment]
Ran into the same issue.  In my case when using `https://api.fonts.coollabs.io/css2?family=Kiwi+Maru&family=Stick&display=swap`.  When I looked at the result, I only saw Kiwi Maru.  

Shown Here:
![image](https://github.com/coollabsio/fonts/assets/2819458/ea402539-aee5-412b-a378-fa36cfa45652)

I swapped the order thinking it would show me Stick using `https://api.fonts.coollabs.io/css2?family=Stick&family=Kiwi+Maru&display=swap` and it gave me Stick only and not Kiwi Maru. 

Shown here:
![image](https://github.com/coollabsio/fonts/assets/2819458/b3b904bb-a7ef-4a7f-bf67-d1f2de51a056)


However, if I made the font "Stick" lowercase, it works.  So `https://api.fonts.coollabs.io/css2?family=stick&family=Kiwi+Maru&display=swap` works. 

Shown here:
![image](https://github.com/coollabsio/fonts/assets/2819458/5d91888b-d454-4dae-9a52-8953ff41753e)

Not sure if this helps, but wanted to add this in case it helps narrow down the issue.

**Comment by andrasbacsai** [comment]
Fixed a lot of issues. It should work now. If not, please open an issue.
