### ISSUE TITLE
Warning when loading font

### ISSUE THREAD

**Issue by rizrmd** [coollabsio/fonts#18]
Hi!

 I got these warning when replacing fonts.googleapis.com with api.fonts.coollabs.io:

<img width="1459" alt="image" src="https://github.com/coollabsio/fonts/assets/126301/ff2269f1-8ff9-4b85-b9c0-e078e42f5d1c">

I am using it like this: 
<img width="539" alt="image" src="https://github.com/coollabsio/fonts/assets/126301/aad71076-603a-4867-9d25-d58bb427efb5">

**Comment by andrasbacsai** [comment]
Not sure what could be the problem, but it is probably related on how you change the url and not in our side.
