### ISSUE TITLE
404 Error for the two google fonts i tried 

### ISSUE THREAD

**Issue by clevermissfox** [coollabsio/fonts#19]
Instead of this in the `<head>`
```html    
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100..900;1,100..900&display=swap"
    rel="stylesheet">```
I put 
```html
<link rel="preconnect" href="https://api.fonts.coollabs.io" crossorigin />
<link href="https://api.fonts.coollabs.io/css2?family=Jost:ital,wght@0,100..900;1,100..900&display=swap"
        rel="stylesheet">
```

and got 404 error. Same when i tried with [Mulish](https://fonts.google.com/specimen/Mulish) and [Karla](https://fonts.google.com/specimen/Karla). 

Would love to use this resource esp for quick and dirty projects on codepen or [iCodeThis](https://icodethis.com) where i cant self host typefaces. Maybe the issue is with variable fonts?

**Comment by andrasbacsai** [comment]
Fixed a lot of issues. It should work now. If not, please open an issue.
