### ISSUE TITLE
GET https://cdn.fonts.coollabs.io/ net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by micisse** [coollabsio/fonts#20]
There seems to be an accessibility problem with urls/api.

[https://cdn.fonts.coollabs.io/roboto/normal/100;300;400;500;700;900.woff2](https://cdn.fonts.coollabs.io/roboto/normal/100;300;400;500;700;900.woff2)

![Image](https://github.com/user-attachments/assets/672933b5-6e30-4ec8-a150-1d603a3808ad)

![Image](https://github.com/user-attachments/assets/1ed60cbf-94cb-4e51-887b-c3ce45250ac8)

![Image](https://github.com/user-attachments/assets/a245f278-2c24-4802-a4f3-108571aed3ed)

![Image](https://github.com/user-attachments/assets/bf3bcfdd-d755-4bfd-9259-b5012da33cfd)

**Comment by andrasbacsai** [comment]
Oh, I see it. fixing it!

**Comment by andrasbacsai** [comment]
It is fixed, sorry about it.
