### ISSUE TITLE
Not getting the variable google fonts ive tried

### ISSUE THREAD

**Issue by clevermissfox** [coollabsio/fonts#21]
I had [opened an issue awhile back](https://github.com/coollabsio/fonts/issues/19?notification_referrer_id=NT_kwDOB3Ztk7UxMTU4MjE4NDYxNzoxMjUyMDE4MTE#issuecomment-2553333394); it was just closed and i was told to open a new issue if it still didnt work. 

Just tested on this [codepen](https://codepen.io/Miss-Fox/pen/ogvWGdd) and although it looks like some of the font properties are being used ('jost' looks more compact than the other two) its still not bringing in the correct fonts.

**Comment by andrasbacsai** [comment]
Can you please check it now? I made a few updates and fixes.

**Comment by clevermissfox** [comment]
@andrasbacsai yes it looks like its working!! I linked the codepen in case that helped with console errors or testing but by George you did it! Thank you!!
