### ISSUE TITLE
in my hosts file

### ISSUE THREAD

**Issue by justthisguy** [coollabsio/fonts#6]
Very cool!  I like your thinking.  All your documentation talks about when I am building a site how I can use Coollabs fonts instead of google's which is great.

Something else I would like to do is put an IP address in my hosts file for google fonts:

w.x.y.z  fonts.googleapis.com
w.x.y.z  fonts.gstatic.com

Is this possible?  If yes, what IP address can be used?

**Comment by daanschenkel** [comment]
This is the ip used by the website: 84.17.46.53, but this is just a general ip for bunny.net, so dont think so
