### ISSUE TITLE
Bug in some multiple requests

### ISSUE THREAD

**Issue by jeff-at-livecanvas** [coollabsio/fonts#7]
First of all. Your project is fantastic and very useful.
I'm trying to use it in our [Picostrap Theme](https://picostrap.com/)  
There is a lot of GDPR compliance concern regarding usage of Google Fonts on the web.
Your solution is really clever and so much easier to implement, compared to locally hosting the fonts.

Tinkering with your service I think I've found a bug.
Some requests dealing with multiple fonts, when not including weights, apparently fail.

One example:
https://api.fonts.coollabs.io/css2?family=Playfair+Display&family=Josefin+Sans&display=swap

**Returns Playfair Display (correctly)  and Montserrat(?)**

To compare, the corresponding Google URL,
https://fonts.googleapis.com/css2?family=Playfair+Display&family=Josefin+Sans&display=swap
works as expected.

Thanks so much again for your project, and for your time looking into this.

**Comment by jeff-at-livecanvas** [comment]
One more interesting case:

https://api.fonts.coollabs.io/css2?family=Barlow+Semi+Condensed:wght@700&family=Abhaya+Libre&display=swap

Here, removing the weight fixes the issue apparently.

**Comment by andrasbacsai** [comment]
Nice findings! I will check them!

**Comment by andrasbacsai** [comment]
Sorry for the late answer. I think this is already solved, I just forgot to write here (oops). Could you please check?

**Comment by jeff-at-livecanvas** [comment]
Hello Andras,
looks like it's working fine now. Amazing!
Thank you again for your effort in maintaining this useful project.
