### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by zdat** [coollabsio/fonts#9]
I feel stupid but, how exactly do I do this?

I've read the [how to use](https://github.com/coollabsio/fonts#how-to-use) but I still don't know.

This isn't fully related to this, but Ideally I wanted to block all remote fonts on all websites and have my "locally hosted" (google) fonts take over, but I'm not sure if that's possible? I'm not sure how to "locally host" fonts. If that isn't possible, I would like to set this up instead.

Can someone tell me if I even have the right way of thinking towards this stuff? Thanks.

**Comment by poberbeck** [comment]
Hey @zdat 😁
do I understand it right, that you want to block the loading of fonts, for example on the YouTube website? This is indeed not really possible. You could block any request to am external server like the Google fonts server with a PiHole or something like this.
Coollabs fonts is meant to replace google fonts when you create a website. For example, you are creating a website for a blog and want to use the `Roboto` font family. Then you could include the font family via Google fonts. But then the font would be loaded through Google servers. Or you could use coollabs fonts. In this case, it would be loaded via privacy-friendly server.
I hope I could bring you a bit of light into the darkness.
